remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Automated Navigation Drone - Weather Processing"
description:"Our mission is to provide an automated computer controlled flight-traversing drone that can travel and land amongst aerial traffic safely through any/all weather conditions and reliably without an operator"
